"""Ajout du multi-boutiques (shop_id)

Revision ID: 37fa61ecb26e
Revises: 
Create Date: 2026-03-03 00:05:41.807082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37fa61ecb26e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('unique_category_per_shop', ['name', 'shop_id'])
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'shops', ['shop_id'], ['id'])

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('unique_phone_per_shop', ['phone', 'shop_id'])
        batch_op.create_foreign_key(None, 'shops', ['shop_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'shops', ['shop_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('unique_product_per_shop', ['name', 'shop_id'])
        batch_op.create_foreign_key(None, 'shops', ['shop_id'], ['id'])

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'])
        batch_op.create_foreign_key(None, 'shops', ['shop_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'shops', ['shop_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('shop_id')

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('order_id')
        batch_op.drop_column('shop_id')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('unique_product_per_shop', type_='unique')
        batch_op.drop_column('shop_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('shop_id')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('unique_phone_per_shop', type_='unique')
        batch_op.drop_column('shop_id')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('unique_category_per_shop', type_='unique')
        batch_op.drop_column('created_by')
        batch_op.drop_column('shop_id')

    # ### end Alembic commands ###
